# Generated by Django 3.2.4 on 2021-06-27 12:50

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0008_owner_products'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='CartSystem',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('quantity', models.IntegerField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('date', models.CharField(max_length=100)),
                ('payment_method', models.CharField(max_length=100)),
                ('card_payment', models.CharField(max_length=100)),
                ('delivery_status', models.CharField(max_length=100)),
                ('order_id', models.CharField(max_length=100)),
                ('owner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.owner_table')),
                ('product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.owner_products')),
                ('user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
        ),
    ]
