# Generated by Django 3.2.4 on 2021-06-21 14:26

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Owner_table',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('owner_name', models.CharField(max_length=100)),
                ('owner_username', models.CharField(max_length=100)),
                ('owner_email', models.EmailField(max_length=254)),
                ('owner_password', models.CharField(max_length=100)),
                ('owner_store_name', models.CharField(max_length=100)),
                ('owner_store_type', models.CharField(max_length=100)),
                ('owner_store_password', models.CharField(max_length=100)),
            ],
        ),
    ]
