# Generated by Django 3.2.4 on 2021-06-23 12:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('itme_name', models.CharField(max_length=100)),
                ('item_picture_path', models.CharField(max_length=100)),
                ('Quantity', models.CharField(max_length=100)),
                ('price_to_sold', models.CharField(max_length=100)),
                ('Quantity_type', models.CharField(max_length=100)),
            ],
        ),
    ]
