# Generated by Django 3.2.4 on 2021-06-23 14:13

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0002_owner_products'),
    ]

    operations = [
        migrations.AddField(
            model_name='owner_products',
            name='owner_id',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.owner_table'),
        ),
    ]
