# Generated by Django 3.2.4 on 2021-06-23 14:23

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0003_owner_products_owner_id'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner_products',
            old_name='Quantity',
            new_name='quantity',
        ),
    ]
