# Generated by Django 3.2.4 on 2021-06-23 14:37

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0004_rename_quantity_owner_products_quantity'),
    ]

    operations = [
        migrations.RenameField(
            model_name='owner_products',
            old_name='itme_name',
            new_name='item_name',
        ),
    ]
