# Generated by Django 3.2.4 on 2021-06-23 14:55

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0005_rename_itme_name_owner_products_item_name'),
    ]

    operations = [
        migrations.AlterField(
            model_name='owner_products',
            name='price_to_sold',
            field=models.IntegerField(),
        ),
        migrations.AlterField(
            model_name='owner_products',
            name='quantity',
            field=models.IntegerField(),
        ),
    ]
