# Generated by Django 3.2.4 on 2021-06-23 14:56

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0006_auto_20210623_1955'),
    ]

    operations = [
        migrations.DeleteModel(
            name='Owner_Products',
        ),
    ]
