# Generated by Django 3.2.4 on 2021-06-23 14:56

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('store', '0007_delete_owner_products'),
    ]

    operations = [
        migrations.CreateModel(
            name='Owner_Products',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('item_name', models.CharField(max_length=100)),
                ('item_picture_path', models.CharField(max_length=100)),
                ('quantity', models.IntegerField()),
                ('price_to_sold', models.IntegerField()),
                ('Quantity_type', models.CharField(max_length=100)),
                ('owner_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.owner_table')),
            ],
        ),
    ]
