# Generated by Django 3.2.4 on 2021-06-24 13:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('store', '0008_owner_products'),
        ('user', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Selling_history',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('Quantity_sold', models.IntegerField()),
                ('Date', models.DateField()),
                ('owner_product_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='store.owner_products')),
                ('owner_user_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='user.user')),
            ],
        ),
    ]
