# Generated by Django 3.2.4 on 2021-06-24 17:38

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('history', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='selling_history',
            name='Date',
            field=models.CharField(max_length=12),
        ),
    ]
