# Generated by Django 3.2.4 on 2021-07-10 18:16

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('cart', '0002_alter_cartsystem_quantity'),
    ]

    operations = [
        migrations.CreateModel(
            name='Biker_Profile',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('name', models.CharField(max_length=100)),
                ('email', models.EmailField(max_length=254)),
                ('username', models.CharField(max_length=100)),
                ('number', models.BigIntegerField()),
                ('password', models.CharField(max_length=100)),
            ],
        ),
        migrations.CreateModel(
            name='OrderBiker',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('delivery_status', models.CharField(max_length=100)),
                ('address', models.CharField(max_length=100)),
                ('contact', models.BigIntegerField()),
                ('biker_id', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='biker.biker_profile')),
                ('order_id_to_biker', models.ForeignKey(null=True, on_delete=django.db.models.deletion.SET_NULL, to='cart.cartsystem')),
            ],
        ),
    ]
